export const sizeItems = {
  Small: [
    { name: 'A', weight: 6, value: 5 },
    { name: 'B', weight: 4, value: 3 },
    { name: 'C', weight: 3, value: 1 },
    { name: 'D', weight: 2, value: 3 },
    { name: 'E', weight: 5, value: 6 },
    // Add more items as needed
  ],
  Medium: [
    { name: 'F', weight: 8, value: 7 },
    { name: 'G', weight: 5, value: 4 },
    { name: 'H', weight: 3, value: 2 },
  ],
  Large: [
    { name: 'A', weight: 6, value: 5 },
    { name: 'B', weight: 4, value: 3 },
    { name: 'C', weight: 3, value: 1 },
    { name: 'D', weight: 2, value: 3 },
    { name: 'E', weight: 5, value: 6 },
    { name: 'F', weight: 7, value: 2 },
    { name: 'G', weight: 8, value: 9 },
    { name: 'H', weight: 3, value: 4 },
    { name: 'I', weight: 1, value: 8 },
    { name: 'J', weight: 6, value: 7 },
    { name: 'K', weight: 4, value: 6 },
    { name: 'L', weight: 2, value: 5 },
    { name: 'M', weight: 5, value: 9 },
    { name: 'N', weight: 3, value: 2 },
    { name: 'O', weight: 7, value: 4 },
    { name: 'P', weight: 1, value: 7 },
    { name: 'Q', weight: 4, value: 3 },
    { name: 'R', weight: 6, value: 8 },
    { name: 'S', weight: 2, value: 1 },
    { name: 'T', weight: 8, value: 6 },
    { name: 'U', weight: 5, value: 4 },
    { name: 'V', weight: 3, value: 7 },
    { name: 'W', weight: 7, value: 2 },
    { name: 'X', weight: 1, value: 5 },
    { name: 'Y', weight: 4, value: 9 },
    { name: 'Z', weight: 6, value: 3 },
    { name: 'AA', weight: 2, value: 7 },
    { name: 'AB', weight: 8, value: 4 },
    { name: 'AC', weight: 3, value: 6 },
    { name: 'AD', weight: 5, value: 1 },
    { name: 'AE', weight: 1, value: 8 },
    { name: 'AF', weight: 7, value: 5 },
    { name: 'AG', weight: 4, value: 2 },
    { name: 'AH', weight: 6, value: 9 },
    { name: 'AI', weight: 3, value: 1 },
    { name: 'AJ', weight: 2, value: 4 },
    { name: 'AK', weight: 5, value: 7 },
    { name: 'AL', weight: 8, value: 3 },
    { name: 'AM', weight: 1, value: 6 },
    { name: 'AN', weight: 4, value: 9 },
    { name: 'AO', weight: 6, value: 2 },
    { name: 'AP', weight: 3, value: 7 },
    { name: 'AQ', weight: 5, value: 1 },
    { name: 'AR', weight: 2, value: 8 },
    { name: 'AS', weight: 7, value: 4 },
    { name: 'AT', weight: 1, value: 3 },
    { name: 'AU', weight: 4, value: 6 },
    { name: 'AV', weight: 8, value: 2 },
    { name: 'AW', weight: 3, value: 5 },
    { name: 'AX', weight: 6, value: 9 },
    { name: 'AY', weight: 2, value: 1 },
    { name: 'AZ', weight: 5, value: 8 },
    { name: 'BA', weight: 8, value: 3 },
    { name: 'BB', weight: 4, value: 7 },
    { name: 'BC', weight: 6, value: 1 },
    { name: 'BD', weight: 3, value: 5 },
    { name: 'BE', weight: 7, value: 9 },
    { name: 'BF', weight: 2, value: 4 },
    { name: 'BG', weight: 5, value: 6 },
    { name: 'BH', weight: 1, value: 8 },
    { name: 'BI', weight: 8, value: 3 },
    { name: 'BJ', weight: 4, value: 2 },
    { name: 'BK', weight: 6, value: 7 },
    { name: 'BL', weight: 3, value: 1 },
    { name: 'BM', weight: 2, value: 5 },
    { name: 'BN', weight: 5, value: 9 },
    { name: 'BO', weight: 1, value: 4 },
    { name: 'BP', weight: 7, value: 8 },
    { name: 'BQ', weight: 4, value: 6 },
    { name: 'BR', weight: 6, value: 2 },
    { name: 'BS', weight: 2, value: 9 },
    { name: 'BT', weight: 5, value: 1 },
    { name: 'BU', weight: 8, value: 4 },
    { name: 'BV', weight: 3, value: 7 },
    { name: 'BW', weight: 7, value: 5 },
    { name: 'BX', weight: 4, value: 1 },
    { name: 'BY', weight: 1, value: 8 },
    { name: 'BZ', weight: 6, value: 3 },
  ],
};
